#!/bin/bash

ICO="network-wired-symbolic"
ip=$(ifconfig "eth0" |grep "inet " | awk '{print $2}')
#echo "%{F#2495e7} %{F#ffffff}$(/usr/sbin/ifconfig eth0 | grep "inet " | awk '{print $2}')%{u-}"

printf "<txt>${ip}</txt>"
printf "<icon>${ICO}</icon>"
printf "<tool>Eth IP</tool>"